import { NextPage } from 'next'
import Head from 'next/head'

import { Container, Heading, Input, VStack } from '@chakra-ui/react'
import { Controller, FormProvider, useForm } from 'react-hook-form'

import { AdsSearch } from '@src/components'
import { AuthProvider } from '@src/context'

type FieldValues = {
  city: string
  search: string
}

const Home: NextPage = () => {
  const form = useForm<FieldValues>({
    defaultValues: {
      city: 'Bordeaux',
      search: '',
    },
  })

  const values = form.watch()

  return (
    <AuthProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container as={VStack} alignItems="stretch" flex={1} py={8} maxW="container.md" spacing={4}>
        <Heading size="md" textAlign="center">
          Recherche d&apos;annonces
        </Heading>

        <FormProvider {...form}>
          <Controller
            name="search"
            render={({ field }) => (
              <Input
                bg="white"
                {...field}
                // onChange={debounce(field.onChange, 300)}
                placeholder="Rechercher une offre"
                type="text"
              />
            )}
          />

          <AdsSearch {...values} />
        </FormProvider>
      </Container>
    </AuthProvider>
  )
}

export default Home
